print("<!DOCTYPE html>")
print("<html lang='en'>")
print("\t<head>")
print("\t\t<meta charset='UTF-8'>")        
print("\t\t<meta http-equiv='X-UA-Compatible' content='ie=edge'>")      
print("\t\t<title>Table Of Countries</title>")        
print("\t</head>")
print("\t<body>")
print("\t\t<h1>HTML sivu on tehty kokonaan Pythonilla!</h1>")
print("\t\t<table border='1' width='70%' style='border-collapse: collapse;'>")
print("\t\t\t<thead>")
print("\t\t\t\t<tr>")
print("\t\t\t\t\t<th>Country</th><th>Capital</th>")
print("\t\t\t\t</tr>")
print("\t\t\t</thead>")
print("\t\t\t\t<tr>")
print("\t\t\t\t\t<td>Finland</td><td>Helsinki</td>")
print("\t\t\t\t</tr>")
print("\t\t\t\t<tr>")
print("\t\t\t\t\t<td>France</td><td>Paris</td>")
print("\t\t\t\t</tr>")
print("\t\t</table>")
print("\t\t<h2>Taulujen viivat helpottavat taulun hahmottamista.</h2>")
print("\t</body>")    
print("</html>")
